# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-31 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190529_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='id',
        ),
        migrations.AlterField(
            model_name='fav',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='fav',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='fav',
            name='poiID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
